pak -f default/cat.js /windo_syl/prog
pak -f default/cd.js /windo_syl/prog
pak -f default/help.js /windo_syl/prog
pak -f default/help.txt /windo_syl
pak -f default/ls.js /windo_syl/prog
pak -f default/mkdir.js /windo_syl/prog
pak -f default/mkf.js /windo_syl/prog
pak -f default/mv.js /windo_syl/prog
pak -f default/rm.js /windo_syl/prog
